#!/usr/bin/env bash

# Set up autograder files
ln -s $(which python3) /usr/bin/python

rm -Rf $( find /autograder/submission/cloudysky -name 'test_*.py' )  
rm -Rf $( find /autograder/submission/ -name 'test_*.py' )  

cp -r /autograder/submission/cloudysky /autograder/source

echo "PRAGMA wal_checkpoint(FULL);" | sqlite3 /autograder/source/cloudysky/db.sqlite3

cd /autograder/source

rm -Rf /autograder/source/examples/

python3 run_tests.py

