#!/usr/bin/env bash

# Set up autograder files
ln -s $(which python3) /usr/bin/python

cp -r /autograder/submission/uncommondata /autograder/source

cd /autograder/source

rm -Rf /autograder/source/examples/  # may contain tests that I don't want to run

rm -Rf /autograder/source/uncommondata/app/migrations  # can cause problems 

python3 run_tests.py

