
runserver:
	python3 manage.py runserver

clean:
	-rm -Rf */__pycache__ */*/__pycache__
	-rm -Rf */migrations

migrate:
	python3 manage.py makemigrations
	python3 manage.py migrate

shell:
	python3 manage.py shell
