#!/usr/bin/env bash

# Set up autograder files
ln -s $(which python3) /usr/bin/python

cp -r /autograder/submission/cloudysky /autograder/source

cd /autograder/source

rm -Rf /autograder/source/examples/

python3 run_tests.py

